apiVersion: v1
kind: Service
metadata:
    name: "myk8scluster-c7d4"
    labels:
        app: "myk8scluster-c7d4"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myk8scluster-c7d4"